### ISSUE TITLE
nothing warns you if you don't have python-yaml installed

### ISSUE THREAD

**Issue by gregsfortytwo** [ceph/downburst#2]
gregf@pudgy:~/src/downburst [master]$ ./virtualenv/bin/downburst create downburst-test-01
Traceback (most recent call last):
  File "./virtualenv/bin/downburst", line 9, in <module>
    load_entry_point('downburst==0.0.1', 'console_scripts', 'downburst')()
  File "/home/gregf/src/downburst/downburst/cli.py", line 48, in main
    args = parse_args()
  File "/home/gregf/src/downburst/downburst/cli.py", line 32, in parse_args
    fn = ep.load()
  File "/home/gregf/src/downburst/virtualenv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1989, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/home/gregf/src/downburst/downburst/create.py", line 7, in <module>
    from . import iso
  File "/home/gregf/src/downburst/downburst/iso.py", line 7, in <module>
    from . import meta
  File "/home/gregf/src/downburst/downburst/meta.py", line 2, in <module>
    import yaml
ImportError: No module named yaml

:(

**Comment by kshtsk** [comment]
Should it? All dependencies are supposed to be satisfied by bootstrap I guess.
